import os 
os.system("sudo apt-get update")
os.system("sudo apt-get install docker.io")
os.system("sudo systemctl enable docker")
os.system("curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add")
os.system("sudo apt-add-repository 'deb http://apt.kubernetes.io/ kubernetes-xenial main'")
os.system("sudo apt-get install kubeadm kubelet kubectl")
os.system("sudo apt-mark hold kubeadm kubelet kubectl")
os.system("sudo hostnamectl set-hostname master-node")
os.system("sudo cp daemon.json  /etc/docker/")
os.system("sudo systemctl restart docker ")
os.system("sudo kubeadm init --pod-network-cidr=10.244.0.0/16")
os.system("mkdir -p $HOME/.kube")
os.system("sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config")
os.system("sudo chown $(id -u):$(id -g) $HOME/.kube/config")
os.system("kubectl get nodes")
os.system("sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml")
print("K8s Master Is Succefully Created ....... Master is Ready For USE !!!!!")

